"""Tests to make sure some files are being generated by the \
save participant files function."""
from pathlib import Path

from download_tools.save_participant_files import save_participant_files


def test_save_participant_files(test_case):
    """Tests save_participant_files to make sure files are generated."""
    example_participant_dicts, experiment_name, labeller_path = test_case
    parent_dir = Path(__file__).parents[0]
    save_path = parent_dir / "data" / "human"
    save_participant_files(
        example_participant_dicts,
        experiment_name,
        labeler=labeller_path,
        save_path=save_path,
    )
    assert any((save_path / f"{experiment_name}").iterdir()) is True
